# Generated by Django 3.1.2 on 2020-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201211_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='address_line1',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='career_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Intermediate'), (1, 'Experienced Professional'), (2, 'Entry Level'), (3, 'Department Head'), (4, 'GM / CEO / Country Head')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Non-matriculation'), (1, 'Matriculation/O-level'), (2, 'Intermediate/A-level'), (3, 'Bachelors'), (4, 'Masters'), (5, 'MPhil/MS'), (6, 'PhD/Doctorate'), (7, 'Certification'), (8, 'Diploma'), (9, 'Short Course')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expected_salary',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 5000), (2, 10000), (3, 15000), (4, 20000), (5, 25000), (6, 30000), (7, 35000), (8, 40000), (9, 45000), (10, 50000), (11, 55000), (12, 60000), (13, 65000), (14, 70000), (15, 75000), (16, 80000), (17, 85000), (18, 90000), (19, 95000), (20, 100000), (21, 105000), (22, 110000), (23, 115000), (24, 120000), (25, 125000), (26, 130000), (27, 135000), (28, 140000), (29, 145000), (30, 150000), (31, 155000), (32, 160000), (33, 165000), (34, 170000), (35, 175000), (36, 180000), (37, 185000), (38, 190000), (39, 195000), (40, 200000), (41, 205000), (42, 210000), (43, 215000), (44, 220000), (45, 225000), (46, 230000), (47, 235000), (48, 240000), (49, 245000)], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(blank=True, choices=[(1, '1 years'), (2, '2 years'), (3, '3 years'), (4, '4 years'), (5, '5 years'), (6, '6 years'), (7, '7 years'), (8, '8 years'), (9, '9 years'), (10, '10 years'), (11, '11 years'), (12, '12 years'), (13, '13 years'), (14, '14 years'), (15, '15 years'), (16, '16 years'), (17, '17 years'), (18, '18 years'), (19, '19 years'), (20, '20 years'), (21, '21 years'), (22, '22 years'), (23, '23 years'), (24, '24 years'), (25, '25 years'), (26, '26 years'), (27, '27 years'), (28, '28 years'), (29, '29 years'), (30, '30 years'), (31, '31 years'), (32, '32 years'), (33, '33 years'), (34, '34 years'), (35, '35 years')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'No preference'), (1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Married'), (1, 'Single'), (2, 'Widowed'), (3, 'Separated')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_job_city',
            field=models.IntegerField(blank=True, choices=[(1, 'Karachi'), (2, 'Lahore'), (3, 'Sialkot City'), (4, 'Faisalabad'), (5, 'Rawalpindi'), (6, 'Peshawar'), (7, 'Saidu Sharif'), (8, 'Multan'), (9, 'Gujranwala'), (10, 'Islamabad'), (11, 'Quetta'), (12, 'Bahawalpur'), (13, 'Sargodha'), (14, 'New Mirpur'), (15, 'Chiniot'), (16, 'Sukkur'), (17, 'Larkana'), (18, 'Shekhupura'), (19, 'Jhang City'), (20, 'Rahimyar Khan'), (21, 'Gujrat'), (22, 'Kasur'), (23, 'Mardan'), (24, 'Mingaora'), (25, 'Dera Ghazi Khan'), (26, 'Nawabshah'), (27, 'Sahiwal'), (28, 'Mirpur Khas'), (29, 'Okara'), (30, 'Mandi Burewala'), (31, 'Jacobabad'), (32, 'Saddiqabad'), (33, 'Kohat'), (34, 'Muridke'), (35, 'Muzaffargarh'), (36, 'Khanpur'), (37, 'Gojra'), (38, 'Mandi Bahauddin'), (39, 'Abbottabad'), (40, 'Dadu'), (41, 'Khuzdar'), (42, 'Pakpattan'), (43, 'Tando Allahyar'), (44, 'Vihari'), (45, 'Jaranwala'), (46, 'Kamalia'), (47, 'Kot Addu'), (48, 'Nowshera'), (49, 'Swabi'), (50, 'Dera Ismail Khan'), (51, 'Chaman'), (52, 'Charsadda'), (53, 'Kandhkot'), (54, 'Hasilpur'), (55, 'Muzaffarabad'), (56, 'Mianwali'), (57, 'Jalalpur Jattan'), (58, 'Bhakkar'), (59, 'Zhob'), (60, 'Kharian'), (61, 'Mian Channun'), (62, 'Jamshoro'), (63, 'Pattoki'), (64, 'Harunabad'), (65, 'Toba Tek Singh'), (66, 'Shakargarh'), (67, 'Hujra Shah Muqim'), (68, 'Kabirwala'), (69, 'Mansehra'), (70, 'Lala Musa'), (71, 'Nankana Sahib'), (72, 'Bannu'), (73, 'Timargara'), (74, 'Parachinar'), (75, 'Gwadar'), (76, 'Abdul Hakim'), (77, 'Hassan Abdal'), (78, 'Tank'), (79, 'Hangu'), (80, 'Risalpur Cantonment'), (81, 'Karak'), (82, 'Kundian'), (83, 'Umarkot'), (84, 'Chitral'), (85, 'Dainyor'), (86, 'Kulachi'), (87, 'Kotli'), (88, 'Gilgit'), (89, 'Hyderabad City'), (90, 'Narowal'), (91, 'Khairpur Mir’s'), (92, 'Khanewal'), (93, 'Jhelum'), (94, 'Haripur'), (95, 'Shikarpur'), (96, 'Rawala Kot'), (97, 'Hafizabad'), (98, 'Lodhran'), (99, 'Malakand'), (100, 'Attock City'), (101, 'Batgram'), (102, 'Matiari'), (103, 'Ghotki'), (104, 'Naushahro Firoz'), (105, 'Alpurai'), (106, 'Bagh'), (107, 'Daggar'), (108, 'Bahawalnagar'), (109, 'Leiah'), (110, 'Tando Muhammad Khan'), (111, 'Chakwal'), (112, 'Khushab'), (113, 'Badin'), (114, 'Lakki'), (115, 'Rajanpur'), (116, 'Dera Allahyar'), (117, 'Shahdad Kot'), (118, 'Pishin'), (119, 'Sanghar'), (120, 'Upper Dir'), (121, 'Thatta'), (122, 'Dera Murad Jamali'), (123, 'Kohlu'), (124, 'Mastung'), (125, 'Dasu'), (126, 'Athmuqam'), (127, 'Loralai'), (128, 'Barkhan'), (129, 'Musa Khel Bazar'), (130, 'Ziarat'), (131, 'Gandava'), (132, 'Sibi'), (133, 'Dera Bugti'), (134, 'Eidgah'), (135, 'Turbat'), (136, 'Uthal'), (137, 'Khuzdar'), (138, 'Chilas'), (139, 'Kalat'), (140, 'Panjgur'), (141, 'Gakuch'), (142, 'Qila Saifullah'), (143, 'Kharan'), (144, 'Aliabad'), (145, 'Awaran'), (146, 'Dalbandin')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_job_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
