# Generated by Django 3.1.2 on 2021-02-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201217_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='linked_in',
        ),
    ]
