# Generated by Django 3.1.2 on 2021-02-05 17:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210205_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='PK', max_length=2, null=True),
        ),
    ]
