# Generated by Django 3.1.2 on 2021-03-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_jobseekerprofile_projects_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
