# Generated by Django 3.1.2 on 2021-03-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210301_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
