# Generated by Django 3.1.2 on 2021-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_reference_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
