# Generated by Django 3.1.2 on 2020-10-22 00:31

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_designation', models.CharField(max_length=100)),
                ('job_description', tinymce.models.HTMLField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('salary_type', models.SmallIntegerField(verbose_name=((0, 'Daily'), (1, 'Weekly'), (2, 'Monthly'), (3, 'Yearly')))),
                ('minimum_salary', models.IntegerField(choices=[(19, 'x')])),
                ('career_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.careerlevel')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.experience')),
                ('functional_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.functionalarea')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.industry')),
                ('job_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobshift')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtype')),
            ],
        ),
    ]
