# Generated by Django 3.1.2 on 2020-11-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'industries'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_title',
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'no preference'), (1, 'male'), (2, 'female')], null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 5000), (2, 10000), (3, 15000), (4, 20000), (5, 25000), (6, 30000), (7, 35000), (8, 40000), (9, 45000), (10, 50000), (11, 55000), (12, 60000), (13, 65000), (14, 70000), (15, 75000), (16, 80000), (17, 85000), (18, 90000), (19, 95000), (20, 100000), (21, 105000), (22, 110000), (23, 115000), (24, 120000), (25, 125000), (26, 130000), (27, 135000), (28, 140000), (29, 145000), (30, 150000), (31, 155000), (32, 160000), (33, 165000), (34, 170000), (35, 175000), (36, 180000), (37, 185000), (38, 190000), (39, 195000), (40, 200000), (41, 205000), (42, 210000), (43, 215000), (44, 220000), (45, 225000), (46, 230000), (47, 235000), (48, 240000), (49, 245000)], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='career_level',
            field=models.SmallIntegerField(choices=[(0, 'Intermediate'), (1, 'Experienced Professional'), (2, 'Entry Level'), (3, 'Department Head'), (4, 'GM / CEO / Country Head')], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1 years'), (2, '2 years'), (3, '3 years'), (4, '4 years'), (5, '5 years'), (6, '6 years'), (7, '7 years'), (8, '8 years'), (9, '9 years'), (10, '10 years'), (11, '11 years'), (12, '12 years'), (13, '13 years'), (14, '14 years'), (15, '15 years'), (16, '16 years'), (17, '17 years'), (18, '18 years'), (19, '19 years'), (20, '20 years'), (21, '21 years'), (22, '22 years'), (23, '23 years'), (24, '24 years'), (25, '25 years'), (26, '26 years'), (27, '27 years'), (28, '28 years'), (29, '29 years'), (30, '30 years'), (31, '31 years'), (32, '32 years'), (33, '33 years'), (34, '34 years'), (35, '35 years')], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_shift',
            field=models.SmallIntegerField(choices=[(0, 'all'), (1, 'morning'), (2, 'evening'), (3, 'night')], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.SmallIntegerField(choices=[(0, 'internship'), (1, 'freelancing'), (3, 'contract'), (4, 'full time'), (5, 'part time'), (6, 'permanent')], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_salary',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 5000), (2, 10000), (3, 15000), (4, 20000), (5, 25000), (6, 30000), (7, 35000), (8, 40000), (9, 45000), (10, 50000), (11, 55000), (12, 60000), (13, 65000), (14, 70000), (15, 75000), (16, 80000), (17, 85000), (18, 90000), (19, 95000), (20, 100000), (21, 105000), (22, 110000), (23, 115000), (24, 120000), (25, 125000), (26, 130000), (27, 135000), (28, 140000), (29, 145000), (30, 150000), (31, 155000), (32, 160000), (33, 165000), (34, 170000), (35, 175000), (36, 180000), (37, 185000), (38, 190000), (39, 195000), (40, 200000), (41, 205000), (42, 210000), (43, 215000), (44, 220000), (45, 225000), (46, 230000), (47, 235000), (48, 240000), (49, 245000)], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Monthly'), (3, 'Yearly')], null=True),
        ),
        migrations.DeleteModel(
            name='CareerLevel',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='JobShift',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
