# Generated by Django 3.1.2 on 2020-12-08 15:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201208_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(choices=[(1, 'Karachi'), (2, 'Lahore'), (3, 'Sialkot City'), (4, 'Faisalabad'), (5, 'Rawalpindi'), (6, 'Peshawar'), (7, 'Saidu Sharif'), (8, 'Multan'), (9, 'Gujranwala'), (10, 'Islamabad'), (11, 'Quetta'), (12, 'Bahawalpur'), (13, 'Sargodha'), (14, 'New Mirpur'), (15, 'Chiniot'), (16, 'Sukkur'), (17, 'Larkana'), (18, 'Shekhupura'), (19, 'Jhang City'), (20, 'Rahimyar Khan'), (21, 'Gujrat'), (22, 'Kasur'), (23, 'Mardan'), (24, 'Mingaora'), (25, 'Dera Ghazi Khan'), (26, 'Nawabshah'), (27, 'Sahiwal'), (28, 'Mirpur Khas'), (29, 'Okara'), (30, 'Mandi Burewala'), (31, 'Jacobabad'), (32, 'Saddiqabad'), (33, 'Kohat'), (34, 'Muridke'), (35, 'Muzaffargarh'), (36, 'Khanpur'), (37, 'Gojra'), (38, 'Mandi Bahauddin'), (39, 'Abbottabad'), (40, 'Dadu'), (41, 'Khuzdar'), (42, 'Pakpattan'), (43, 'Tando Allahyar'), (44, 'Vihari'), (45, 'Jaranwala'), (46, 'Kamalia'), (47, 'Kot Addu'), (48, 'Nowshera'), (49, 'Swabi'), (50, 'Dera Ismail Khan'), (51, 'Chaman'), (52, 'Charsadda'), (53, 'Kandhkot'), (54, 'Hasilpur'), (55, 'Muzaffarabad'), (56, 'Mianwali'), (57, 'Jalalpur Jattan'), (58, 'Bhakkar'), (59, 'Zhob'), (60, 'Kharian'), (61, 'Mian Channun'), (62, 'Jamshoro'), (63, 'Pattoki'), (64, 'Harunabad'), (65, 'Toba Tek Singh'), (66, 'Shakargarh'), (67, 'Hujra Shah Muqim'), (68, 'Kabirwala'), (69, 'Mansehra'), (70, 'Lala Musa'), (71, 'Nankana Sahib'), (72, 'Bannu'), (73, 'Timargara'), (74, 'Parachinar'), (75, 'Gwadar'), (76, 'Abdul Hakim'), (77, 'Hassan Abdal'), (78, 'Tank'), (79, 'Hangu'), (80, 'Risalpur Cantonment'), (81, 'Karak'), (82, 'Kundian'), (83, 'Umarkot'), (84, 'Chitral'), (85, 'Dainyor'), (86, 'Kulachi'), (87, 'Kotli'), (88, 'Gilgit'), (89, 'Hyderabad City'), (90, 'Narowal'), (91, 'Khairpur Mir’s'), (92, 'Khanewal'), (93, 'Jhelum'), (94, 'Haripur'), (95, 'Shikarpur'), (96, 'Rawala Kot'), (97, 'Hafizabad'), (98, 'Lodhran'), (99, 'Malakand'), (100, 'Attock City'), (101, 'Batgram'), (102, 'Matiari'), (103, 'Ghotki'), (104, 'Naushahro Firoz'), (105, 'Alpurai'), (106, 'Bagh'), (107, 'Daggar'), (108, 'Bahawalnagar'), (109, 'Leiah'), (110, 'Tando Muhammad Khan'), (111, 'Chakwal'), (112, 'Khushab'), (113, 'Badin'), (114, 'Lakki'), (115, 'Rajanpur'), (116, 'Dera Allahyar'), (117, 'Shahdad Kot'), (118, 'Pishin'), (119, 'Sanghar'), (120, 'Upper Dir'), (121, 'Thatta'), (122, 'Dera Murad Jamali'), (123, 'Kohlu'), (124, 'Mastung'), (125, 'Dasu'), (126, 'Athmuqam'), (127, 'Loralai'), (128, 'Barkhan'), (129, 'Musa Khel Bazar'), (130, 'Ziarat'), (131, 'Gandava'), (132, 'Sibi'), (133, 'Dera Bugti'), (134, 'Eidgah'), (135, 'Turbat'), (136, 'Uthal'), (137, 'Khuzdar'), (138, 'Chilas'), (139, 'Kalat'), (140, 'Panjgur'), (141, 'Gakuch'), (142, 'Qila Saifullah'), (143, 'Kharan'), (144, 'Aliabad'), (145, 'Awaran'), (146, 'Dalbandin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(default='PK', max_length=2),
        ),
    ]
