# Generated by Django 3.1.2 on 2020-12-09 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_auto_20201208_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_salary_minimum', models.IntegerField(choices=[(0, 0), (1, 5000), (2, 10000), (3, 15000), (4, 20000), (5, 25000), (6, 30000), (7, 35000), (8, 40000), (9, 45000), (10, 50000), (11, 55000), (12, 60000), (13, 65000), (14, 70000), (15, 75000), (16, 80000), (17, 85000), (18, 90000), (19, 95000), (20, 100000), (21, 105000), (22, 110000), (23, 115000), (24, 120000), (25, 125000), (26, 130000), (27, 135000), (28, 140000), (29, 145000), (30, 150000), (31, 155000), (32, 160000), (33, 165000), (34, 170000), (35, 175000), (36, 180000), (37, 185000), (38, 190000), (39, 195000), (40, 200000), (41, 205000), (42, 210000), (43, 215000), (44, 220000), (45, 225000), (46, 230000), (47, 235000), (48, 240000), (49, 245000)])),
                ('expected_salary_maximum', models.IntegerField(choices=[(0, 0), (1, 5000), (2, 10000), (3, 15000), (4, 20000), (5, 25000), (6, 30000), (7, 35000), (8, 40000), (9, 45000), (10, 50000), (11, 55000), (12, 60000), (13, 65000), (14, 70000), (15, 75000), (16, 80000), (17, 85000), (18, 90000), (19, 95000), (20, 100000), (21, 105000), (22, 110000), (23, 115000), (24, 120000), (25, 125000), (26, 130000), (27, 135000), (28, 140000), (29, 145000), (30, 150000), (31, 155000), (32, 160000), (33, 165000), (34, 170000), (35, 175000), (36, 180000), (37, 185000), (38, 190000), (39, 195000), (40, 200000), (41, 205000), (42, 210000), (43, 215000), (44, 220000), (45, 225000), (46, 230000), (47, 235000), (48, 240000), (49, 245000)])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
