# Generated by Django 3.1.2 on 2020-12-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20201209_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
