# Generated by Django 3.1.2 on 2020-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20201211_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No preference'), (1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_shift',
            field=models.SmallIntegerField(choices=[(0, 'All'), (1, 'Morning'), (2, 'Evening'), (3, 'Night')], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.SmallIntegerField(choices=[(0, 'Internship'), (1, 'Freelancing'), (3, 'Contract'), (4, 'Full time'), (5, 'Part time'), (6, 'Permanent')], null=True),
        ),
    ]
