# Generated by Django 3.1.2 on 2020-12-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20201211_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50, null=True),
        ),
    ]
